### ISSUE TITLE
Hydra bugs

### ISSUE THREAD

**Issue by alessandro-canevaro** [peterampazzo/dtu-02476#10]
1) In `conv_nn.py` line 22 is `nn.Linear(int_features=out_features1, ...)` instead it should be `nn.Linear(in_features=out_features1, ...)`
2) Same for line 24
3) In `training_config.yaml` line 5 is `outfeatures2: 512`, but in `train_model.py` line 24 is called as `out_features2`
4) I also had some problems with hydra not finding the config folder, do you have the same issue?

**Comment by peterampazzo** [comment]
> 4. I also had some problems with hydra not finding the config folder, do you have the same issue?

I do! I fixed this error while making the Dockerfile, have a look at: 2136d3f.

**Comment by Loic-Ker** [comment]
I corrected the bugs directly inside the develop branch :)

**Comment by alessandro-canevaro** [comment]
Nice!, but are you able to run the code without errors? Because I'm getting this:
```
Traceback (most recent call last):
  File ".\src\models\train_model.py", line 29, in train
    train = torch.load("data/processed/train.pt")
  File "C:\ProgramData\Anaconda3\envs\mlops\lib\site-packages\torch\serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\ProgramData\Anaconda3\envs\mlops\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\Anaconda3\envs\mlops\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/processed/train.pt'
```
which is kinda weird... 
I run some checks with `os.path.isdir()` and it return true for `data/processed/` and false for `data/processed/train.pt`
