### ISSUE TITLE
Add config hyperparameters in predict_model.py

### ISSUE THREAD

**Issue by alessandro-canevaro** [peterampazzo/dtu-02476#13]
maybe use configuration file for this values?

_Originally posted by @peterampazzo in https://github.com/peterampazzo/dtu-02476/pull/12#discussion_r785786768_

**Comment by erlahrafnkels** [comment]
This hasn't been changed. Do we want to make the changes (get values from config) and commit with a PR straight to develop? I can do it if you want.

**Comment by alessandro-canevaro** [comment]
need to check if we can import the config.yaml in gcloud functions
