### ISSUE TITLE
isort and black conflict

### ISSUE THREAD

**Issue by alessandro-canevaro** [peterampazzo/dtu-02476#15]
I ran `tox ./` (in the profiling branch) and isort wants to format the imports as
```
from torch.profiler import (ProfilerActivity, profile, record_function,
                            tensorboard_trace_handler)
```
while black as
```
from torch.profiler import (
    ProfilerActivity,
    profile,
    record_function,
    tensorboard_trace_handler,
)
```
therefore the code never passes the lint checks.

**Comment by peterampazzo** [comment]
wow 🤯

**Comment by peterampazzo** [comment]
please, push your changes so I can have a look

**Comment by alessandro-canevaro** [comment]
it is pushed in the branch profiling
it is the src/profiling/mode_profiling.py file

**Comment by peterampazzo** [comment]
https://github.com/PyCQA/isort/issues/1518#issuecomment-703056188

This solution should solve the error.
